import frappe



@frappe.whitelist(allow_guest=True)
def seach_keywords(q: str):
    try:
        # Get OpenSearch client
        client = frappe.new_doc("Resume").get_opensearch_client()
        index_name = "resumes"

        # OpenSearch query for skills, designations, and companies with prefix matching
        query = {
            "size": 0,
            "_source": False,
            "query": {
                "bool": {
                    "should": [
                        {
                            "nested": {
                                "path": "skills",
                                "query": {
                                    "match_phrase_prefix": {
                                        "skills.skill_name": {
                                            "query": q,
                                            "max_expansions": 50
                                        }
                                    }
                                }
                            }
                        },
                        {
                            "nested": {
                                "path": "experience",
                                "query": {
                                    "match_phrase_prefix": {
                                        "experience.role_position": {
                                            "query": q,
                                            "max_expansions": 50
                                        }
                                    }
                                }
                            }
                        },
                        {
                            "nested": {
                                "path": "experience",
                                "query": {
                                    "match_phrase_prefix": {
                                        "experience.company_name": {
                                            "query": q,
                                            "max_expansions": 50
                                        }
                                    }
                                }
                            }
                        }
                    ],
                    "minimum_should_match": 1
                }
            },
            "aggs": {
                "skill_suggestions": {
                    "nested": {
                        "path": "skills"
                    },
                    "aggs": {
                        "matching_skills": {
                            "filter": {
                                "match_phrase_prefix": {
                                    "skills.skill_name": {
                                        "query": q,
                                        "max_expansions": 50
                                    }
                                }
                            },
                            "aggs": {
                                "skills": {
                                    "terms": {
                                        "field": "skills.skill_name.keyword",
                                        "size": 5
                                    }
                                }
                            }
                        }
                    }
                },
                "designation_suggestions": {
                    "nested": {
                        "path": "experience"
                    },
                    "aggs": {
                        "matching_designations": {
                            "filter": {
                                "match_phrase_prefix": {
                                    "experience.role_position": {
                                        "query": q,
                                        "max_expansions": 50
                                    }
                                }
                            },
                            "aggs": {
                                "designations": {
                                    "terms": {
                                        "field": "experience.role_position.keyword",
                                        "size": 5
                                    }
                                }
                            }
                        }
                    }
                },
                "company_suggestions": {
                    "nested": {
                        "path": "experience"
                    },
                    "aggs": {
                        "matching_companies": {
                            "filter": {
                                "match_phrase_prefix": {
                                    "experience.company_name": {
                                        "query": q,
                                        "max_expansions": 50
                                    }
                                }
                            },
                            "aggs": {
                                "companies": {
                                    "terms": {
                                        "field": "experience.company_name.keyword",
                                        "size": 5
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        # Execute the query against OpenSearch
        response = client.search(index=index_name, body=query)
        
        # Extract suggestions from all three categories
        suggestions = {
            "skills": [],
            "designations": [],
            "companies": []
        }
        if 'aggregations' in response:
            # Extract skills
            skill_buckets = response['aggregations']['skill_suggestions']['matching_skills']['skills']['buckets']
            suggestions['skills'] = [bucket['key'] for bucket in skill_buckets]
            
            # Extract designations
            designation_buckets = response['aggregations']['designation_suggestions']['matching_designations']['designations']['buckets']
            suggestions['designations'] = [bucket['key'] for bucket in designation_buckets]
            
            # Extract companies
            company_buckets = response['aggregations']['company_suggestions']['matching_companies']['companies']['buckets']
            suggestions['companies'] = [bucket['key'] for bucket in company_buckets]
        
        print([(item, key) for key, values in suggestions.items() for item in values])
        return [(item, key) for key, values in suggestions.items() for item in values]

    except Exception as e:
        frappe.log_error(f"Error in seach_keywords: {str(e)}")
        return {"skills": [], "designations": [], "companies": []}

@frappe.whitelist(allow_guest=True)
def seach_skills(q:str):
    skills = [
        "Python", "Java", "JavaScript", "C#", "C++", "Ruby", "PHP", "Go", "Swift", "Kotlin", 
        "SQL", "HTML/CSS", "React", "Angular", "Node.js", "Django", "Flask", "Spring Boot", 
        "ASP.NET", "Docker", "Kubernetes", "Git/GitHub", "CI/CD", "REST APIs", "GraphQL", 
        "Microservices", "Cloud Computing (AWS, Azure, GCP)",
        "Manual Testing", "Automated Testing", "Selenium", "JUnit", "TestNG", "PyTest", 
        "Postman", "JMeter", "LoadRunner", "Cucumber", "Test Cases and Test Plans", 
        "Bug Tracking", "Performance Testing", "API Testing", "Regression Testing", 
        "Integration Testing", "Unit Testing", "End-to-End Testing",
        "Data Analysis", "Data Cleaning", "Data Visualization", "Pandas", "NumPy", "SQL", "R", 
        "Excel", "Tableau", "Power BI", "Machine Learning", "Deep Learning", "TensorFlow", 
        "PyTorch", "Data Mining", "Data Wrangling", "Statistical Analysis", 
        "Predictive Modeling", "Data Warehousing",
        "CI/CD", "Jenkins", "Docker", "Kubernetes", "Ansible", "Terraform", "AWS", "Azure", 
        "GCP", "Bash/Shell Scripting", "Infrastructure as Code (IaC)", 
        "Monitoring and Logging (Prometheus, Grafana)", "Configuration Management", 
        "Version Control (Git)", "Container Orchestration",
        "Linux Administration", "Windows Server", "Bash/Shell Scripting", "Powershell", 
        "Network Configuration", "System Monitoring", "Security Management", 
        "User and Permission Management", "Virtualization (VMware, Hyper-V)", 
        "Backup and Recovery", "Firewall Configuration", "Active Directory", 
        "DNS/DHCP Configuration", "IT Support"
    ]
    filter_data = list(filter(lambda a: q in a, skills))
    return filter_data


@frappe.whitelist(allow_guest=True)
def seach_candidate_location(q:str):
    locations = [
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", 
    "Kolkata", "Pune", "Jaipur", "Surat", "Lucknow", "Kanpur", 
    "Nagpur", "Patna", "Indore", "Bhopal", "Ludhiana", "Agra", 
    "Nashik", "Vadodara", "Faridabad", "Ghaziabad", "Rajkot", 
    "Meerut", "Kochi", "Coimbatore", "Mysore", "Guwahati", 
    "Dehradun", "Ranchi", "Jodhpur", "Gwalior", "Thane", 
    "Visakhapatnam", "Madurai", "Vijayawada", "Chandigarh", 
    "Hubli-Dharwad", "Amritsar", "Raipur", "Bhubaneswar", 
    "Jabalpur", "Guntur", "Noida", "Gurugram", "Aurangabad", 
    "Solapur", "Rajahmundry", "Tirupati", "Mangalore", 
    "Navi Mumbai", "Udaipur", "Vellore", "Jalandhar", 
    "Kota", "Varanasi", "Allahabad", "Bareilly", 
    "Salem", "Tiruchirappalli", "Gaya", "Dhanbad", 
    "Bikaner", "Jammu", "Shimla", "Itanagar", 
    "Shillong", "Aizawl", "Gangtok", "Kohima", 
    "Imphal", "Agartala", "Panaji", "Port Blair", 
    "Daman", "Silvassa", "Kavaratti", "Puducherry"
    ]

    filter_data = list(filter(lambda a: q in a, locations))
    return filter_data




@frappe.whitelist(allow_guest=True)
def seach_candidate_industry(q:str):
    industries = [
    "Information Technology (IT)", "Finance", "Healthcare", 
    "Manufacturing", "Retail", "Education", 
    "Telecommunication", "Hospitality", "Energy", 
    "Transportation and Logistics"
    ]
    filter_data = list(filter(lambda a: q in a, industries))
    return filter_data





@frappe.whitelist(allow_guest=True)
def seach_candidate_company(q:str):
    companies = [
    "Google", "Apple", "Microsoft", 
    "Amazon", "Facebook (Meta)", "Tesla", 
    "IBM", "Intel", "Samsung", 
    "Netflix"
    ]

    filter_data = list(filter(lambda a: q in a, companies))
    return filter_data

@frappe.whitelist(allow_guest=True)
def seach_candidate_designation(q:str):
    designations = [
    "Software Engineer", "Senior Software Engineer", "Lead Developer", 
    "Principal Engineer", "Software Architect", "Technical Lead", 
    "Engineering Manager", "Product Manager", "Project Manager", 
    "Team Lead", "DevOps Engineer", "QA Engineer", 
    "Test Engineer", "Automation Tester", "Data Analyst", 
    "Data Scientist", "Data Engineer", "Machine Learning Engineer", 
    "Business Analyst", "Network Engineer", "System Administrator", 
    "Database Administrator", "UI/UX Designer", "Frontend Developer", 
    "Backend Developer", "Full Stack Developer", "Mobile Developer", 
    "IT Support Specialist", "Technical Support Engineer", "Technical Writer", 
    "Security Analyst", "Penetration Tester", "Cybersecurity Specialist", 
    "IT Consultant", "Solutions Architect", "Cloud Architect", 
    "IT Operations Manager", "Release Manager", "Site Reliability Engineer (SRE)", 
    "Infrastructure Engineer", "Help Desk Technician", "IT Technician"
    ]

    filter_data = list(filter(lambda a: q in a, designations))
    return filter_data



@frappe.whitelist(allow_guest=True)
def seach_candidate_edu_institute(q:str):
    education_institutions = [
    "Massachusetts Institute of Technology (MIT)", "Stanford University", 
    "Harvard University", "California Institute of Technology (Caltech)", 
    "University of Oxford", "University of Cambridge", 
    "University of Chicago", "Princeton University", 
    "Imperial College London", "University College London (UCL)"
    ]
    filter_data = list(filter(lambda a: q in a, education_institutions))
    return filter_data


@frappe.whitelist(allow_guest=True)
def seach_candidate_category(q:str):
    candidate_categories = [
    "Fresher", "Experienced", "Intern", 
    "Junior Developer", "Mid-Level Developer", "Senior Developer", 
    "Team Lead", "Manager", "Executive", 
    "Consultant", "Contractor", "Freelancer", 
    "Part-Time", "Full-Time", "Remote Worker", 
    "On-Site Worker", "Temporary", "Permanent", 
    "Entry-Level", "Mid-Level", "Senior-Level", 
    "Technical", "Non-Technical", "Skilled Worker", 
    "Unskilled Worker", "Supervisor", "Administrator"
]

    filter_data = list(filter(lambda a: q in a, candidate_categories))
    return filter_data


@frappe.whitelist()
def seach_results():
    return [{'id': 1,
  'name': 'Anay Raja',
  'experience': '2y 10m',
  'salary': '₹ 7 Lacs',
  'location': 'Shivpuri',
  'currentJob': 'Ambulance person',
  'company': 'Sandhu, Verma and Bakshi',
  'education': 'B.Tech NIT Trichy, Tiruvottiyur 2020',
  'preferredLocations': ['Chennai', 'Ahmedabad', 'Remote'],
  'keySkills': ['Database Design', 'Mobile App', 'Backend', 'DevOps'],
  'additionalSkills': ['Angular',
   'Docker',
   'Javascript',
   'SQL Server',
   'Java',
   'Python',
   'Software Development'],
  'profileSummary': 'Earum nulla non iure officia repudiandae accusantium. Vel nobis a quia vitae eius.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 0,
  'downloads': 8,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 173,
  'experienceYears': 2,
  'salaryLacs': 7,
  'designation': 'Dramatherapist',
  'department': 'HR',
  'industry': 'IT Services',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 2,
  'name': 'Lakshit Kapadia',
  'experience': '4y 10m',
  'salary': '₹ 38 Lacs',
  'location': 'Tiruppur',
  'currentJob': 'Clinical molecular geneticist',
  'company': 'Gopal and Sons',
  'education': 'M.Tech NIT Trichy, Khora  2023',
  'preferredLocations': ['Chennai', 'Bangalore', 'Remote'],
  'keySkills': ['Database Design',
   'DevOps',
   'API Integration',
   'Frontend Development'],
  'additionalSkills': ['CSS',
   'Software Development',
   'Angular',
   'Javascript',
   'Kubernetes',
   'Java',
   'React'],
  'profileSummary': 'Quibusdam qui alias unde est excepturi. Pariatur voluptas non. Iure reprehenderit dolores.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 0,
  'downloads': 14,
  'hasCV': True,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 198,
  'experienceYears': 4,
  'salaryLacs': 38,
  'designation': 'Engineer, automotive',
  'department': 'Sales',
  'industry': 'E-commerce',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 3,
  'name': 'Netra Thaker',
  'experience': '10y 2m',
  'salary': '₹ 11 Lacs',
  'location': 'Ratlam',
  'currentJob': 'Meteorologist',
  'company': 'Vig, Amble and Barad',
  'education': 'B.E. MIT Pune, Anand 2018',
  'preferredLocations': ['Chennai', 'Ahmedabad', 'Delhi'],
  'keySkills': ['DevOps',
   'Web Development',
   'Frontend Development',
   'Database Design'],
  'additionalSkills': ['Python',
   'Javascript',
   'Java',
   'Software Development',
   'Net Core',
   'SQL Server',
   'CSS'],
  'profileSummary': 'Iure earum sunt minima. In eum ab occaecati alias quasi qui.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 9,
  'downloads': 17,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 81,
  'experienceYears': 10,
  'salaryLacs': 11,
  'designation': 'Further education lecturer',
  'department': 'Engineering',
  'industry': 'Healthcare',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 4,
  'name': 'Ekapad Balakrishnan',
  'experience': '0y 5m',
  'salary': '₹ 28 Lacs',
  'location': 'Sultan Pur Majra',
  'currentJob': 'Conservator, museum/gallery',
  'company': 'Zachariah, Konda and Manda',
  'education': 'B.E. NIT Trichy, Hosur 2021',
  'preferredLocations': ['Remote', 'Tirunelveli', 'Ahmedabad'],
  'keySkills': ['DevOps',
   'Web Development',
   'Frontend Development',
   'Mobile App'],
  'additionalSkills': ['Node.js',
   'HTML',
   'Kubernetes',
   'Angular',
   'Software Development',
   'Net Core',
   'SQL Server'],
  'profileSummary': 'Sint cupiditate unde voluptatem tenetur. Eius blanditiis corporis hic laboriosam assumenda eius.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 3,
  'downloads': 19,
  'hasCV': False,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 74,
  'experienceYears': 0,
  'salaryLacs': 28,
  'designation': 'Chief of Staff',
  'department': 'Engineering',
  'industry': 'IT Services',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 5,
  'name': 'Udarsh Atwal',
  'experience': '2y 6m',
  'salary': '₹ 25 Lacs',
  'location': 'Meerut',
  'currentJob': 'Cartographer',
  'company': 'Dara, Dhar and Ram',
  'education': 'B.E. MIT Pune, Bhiwandi 2020',
  'preferredLocations': ['Chennai', 'Pune', 'Mumbai'],
  'keySkills': ['Database Design', 'Backend', 'Web Development', 'UI/UX'],
  'additionalSkills': ['HTML',
   'Docker',
   'Java',
   'Python',
   'React',
   'Node.js',
   'SQL Server'],
  'profileSummary': 'Nam et sed architecto est. Veritatis recusandae tempora nam ea impedit itaque.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 1,
  'downloads': 13,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 188,
  'experienceYears': 2,
  'salaryLacs': 25,
  'designation': 'Higher education careers adviser',
  'department': 'Engineering',
  'industry': 'IT Services',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 6,
  'name': 'Balvan Chada',
  'experience': '2y 9m',
  'salary': '₹ 12 Lacs',
  'location': 'Malegaon',
  'currentJob': 'Product designer',
  'company': 'Narayanan-Bedi',
  'education': 'B.E. IIT Bombay, Buxar 2018',
  'preferredLocations': ['Pune', 'Bangalore', 'Chennai'],
  'keySkills': ['Frontend Development',
   'API Integration',
   'Mobile App',
   'UI/UX'],
  'additionalSkills': ['Software Development',
   'HTML',
   'Net Core',
   'Python',
   'React',
   'Javascript',
   'Angular'],
  'profileSummary': 'Similique possimus cupiditate nobis. Aliquid officiis dolores a non minus.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 3,
  'downloads': 12,
  'hasCV': False,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 35,
  'experienceYears': 2,
  'salaryLacs': 12,
  'designation': 'Public librarian',
  'department': 'Sales',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 7,
  'name': 'Anjali Oak',
  'experience': '0y 9m',
  'salary': '₹ 18 Lacs',
  'location': 'Asansol',
  'currentJob': 'Public relations officer',
  'company': 'Munshi-Sha',
  'education': 'B.Tech NIT Trichy, Dharmavaram 2019',
  'preferredLocations': ['Chennai', 'Remote', 'Pune'],
  'keySkills': ['Mobile App', 'Backend', 'Database Design', 'Server Side'],
  'additionalSkills': ['React',
   'Node.js',
   'Javascript',
   'Kubernetes',
   'CSS',
   'Docker',
   'Python'],
  'profileSummary': 'Labore occaecati vero vitae laudantium perspiciatis. Amet corporis explicabo rem.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 17,
  'downloads': 6,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 140,
  'experienceYears': 0,
  'salaryLacs': 18,
  'designation': 'Senior tax professional/tax inspector',
  'department': 'Marketing',
  'industry': 'IT Services',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 8,
  'name': 'Irya Mutti',
  'experience': '2y 2m',
  'salary': '₹ 13 Lacs',
  'location': 'Pondicherry',
  'currentJob': 'Location manager',
  'company': 'Solanki-Mani',
  'education': 'M.Tech NIT Trichy, Mathura 2022',
  'preferredLocations': ['Ahmedabad', 'Chennai', 'Tirunelveli'],
  'keySkills': ['UI/UX', 'DevOps', 'Database Design', 'Web Development'],
  'additionalSkills': ['MongoDB',
   'React',
   'Java',
   'Kubernetes',
   'Angular',
   'Javascript',
   'Net Core'],
  'profileSummary': 'Dolor eaque sint sequi error quibusdam.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 11,
  'downloads': 16,
  'hasCV': False,
  'lastModified': 'last week',
  'activeStatus': 'Active today',
  'similarProfiles': 86,
  'experienceYears': 2,
  'salaryLacs': 13,
  'designation': 'English as a second language teacher',
  'department': 'HR',
  'industry': 'IT Services',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 9,
  'name': 'Fariq Dasgupta',
  'experience': '5y 4m',
  'salary': '₹ 27 Lacs',
  'location': 'Patiala',
  'currentJob': 'Electronics engineer',
  'company': 'Gala PLC',
  'education': 'B.Tech IIT Bombay, Rajkot 2023',
  'preferredLocations': ['Remote', 'Delhi', 'Pune'],
  'keySkills': ['API Integration',
   'Backend',
   'Database Design',
   'Frontend Development'],
  'additionalSkills': ['CSS',
   'HTML',
   'Javascript',
   'Python',
   'Angular',
   'Docker',
   'Software Development'],
  'profileSummary': 'Optio occaecati doloribus earum quas. Fuga eaque accusantium.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 1,
  'downloads': 18,
  'hasCV': False,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 142,
  'experienceYears': 5,
  'salaryLacs': 27,
  'designation': 'Civil engineer, consulting',
  'department': 'Engineering',
  'industry': 'Healthcare',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 10,
  'name': 'Saumya De',
  'experience': '7y 7m',
  'salary': '₹ 27 Lacs',
  'location': 'Chennai',
  'currentJob': 'Psychologist, clinical',
  'company': 'Pall, Bhatia and Pall',
  'education': 'B.E. IIT Bombay, Jaunpur 2020',
  'preferredLocations': ['Delhi', 'Chennai', 'Tirunelveli'],
  'keySkills': ['Database Design', 'Web Development', 'UI/UX', 'DevOps'],
  'additionalSkills': ['HTML',
   'Node.js',
   'Javascript',
   'Kubernetes',
   'Docker',
   'MongoDB',
   'SQL Server'],
  'profileSummary': 'Laborum non maiores occaecati dolor. Hic autem cumque eligendi.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 7,
  'downloads': 11,
  'hasCV': True,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 20,
  'experienceYears': 7,
  'salaryLacs': 27,
  'designation': 'Data processing manager',
  'department': 'HR',
  'industry': 'Healthcare',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 11,
  'name': 'Oni Garde',
  'experience': '3y 8m',
  'salary': '₹ 34 Lacs',
  'location': 'Amritsar',
  'currentJob': 'Osteopath',
  'company': 'Doctor, Bhatti and Chakraborty',
  'education': 'M.Tech NIT Trichy, Alappuzha 2020',
  'preferredLocations': ['Pune', 'Ahmedabad', 'Remote'],
  'keySkills': ['Mobile App', 'Server Side', 'UI/UX', 'DevOps'],
  'additionalSkills': ['Net Core',
   'Angular',
   'React',
   'Python',
   'Java',
   'CSS',
   'MongoDB'],
  'profileSummary': 'Veritatis tenetur repudiandae similique nostrum. Sit voluptates aliquam quod excepturi.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 12,
  'downloads': 11,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 122,
  'experienceYears': 3,
  'salaryLacs': 34,
  'designation': 'Engineer, land',
  'department': 'HR',
  'industry': 'Healthcare',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 12,
  'name': 'Jack Dara',
  'experience': '4y 7m',
  'salary': '₹ 11 Lacs',
  'location': 'Tiruvottiyur',
  'currentJob': 'Office manager',
  'company': 'Sama, Ratti and Kala',
  'education': 'B.Tech IIT Bombay, Pali 2021',
  'preferredLocations': ['Delhi', 'Ahmedabad', 'Bangalore'],
  'keySkills': ['Server Side', 'Backend', 'Web Development', 'UI/UX'],
  'additionalSkills': ['HTML',
   'MongoDB',
   'Java',
   'SQL Server',
   'Net Core',
   'Docker',
   'Angular'],
  'profileSummary': 'Vel beatae repellendus voluptates tempora dicta deleniti. Dolorem quae error libero.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 8,
  'downloads': 10,
  'hasCV': False,
  'lastModified': 'last week',
  'activeStatus': 'Active today',
  'similarProfiles': 78,
  'experienceYears': 4,
  'salaryLacs': 11,
  'designation': 'Merchant navy officer',
  'department': 'Engineering',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 13,
  'name': 'Ekiya Mammen',
  'experience': '1y 11m',
  'salary': '₹ 25 Lacs',
  'location': 'Durg',
  'currentJob': 'Arboriculturist',
  'company': 'Dada, Deshmukh and Mukhopadhyay',
  'education': 'B.E. NIT Trichy, Barasat 2020',
  'preferredLocations': ['Pune', 'Ahmedabad', 'Tirunelveli'],
  'keySkills': ['Frontend Development',
   'Backend',
   'Database Design',
   'Mobile App'],
  'additionalSkills': ['HTML',
   'Python',
   'Docker',
   'Net Core',
   'SQL Server',
   'MongoDB',
   'Javascript'],
  'profileSummary': 'Necessitatibus illum ipsa ratione quae. Praesentium voluptates blanditiis veniam et.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 10,
  'downloads': 1,
  'hasCV': False,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 162,
  'experienceYears': 1,
  'salaryLacs': 25,
  'designation': 'Journalist, broadcasting',
  'department': 'Marketing',
  'industry': 'E-commerce',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 14,
  'name': 'Aditya Sura',
  'experience': '0y 4m',
  'salary': '₹ 36 Lacs',
  'location': 'Pimpri-Chinchwad',
  'currentJob': 'Early years teacher',
  'company': 'Mistry-Varughese',
  'education': 'M.Tech MIT Pune, Gopalpur 2018',
  'preferredLocations': ['Bangalore', 'Mumbai', 'Delhi'],
  'keySkills': ['Frontend Development',
   'Server Side',
   'API Integration',
   'Database Design'],
  'additionalSkills': ['Node.js',
   'Net Core',
   'Java',
   'CSS',
   'Kubernetes',
   'SQL Server',
   'MongoDB'],
  'profileSummary': 'Numquam impedit cumque. Ipsam ut exercitationem ipsam excepturi veniam.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 11,
  'downloads': 3,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 112,
  'experienceYears': 0,
  'salaryLacs': 36,
  'designation': 'Conservator, furniture',
  'department': 'Engineering',
  'industry': 'Finance',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 15,
  'name': 'Yachana Mishra',
  'experience': '10y 5m',
  'salary': '₹ 9 Lacs',
  'location': 'Nizamabad',
  'currentJob': 'Audiological scientist',
  'company': 'Chhabra, Tata and Srivastava',
  'education': 'B.E. Parul University, Kirari Suleman Nagar 2018',
  'preferredLocations': ['Pune', 'Bangalore', 'Mumbai'],
  'keySkills': ['Database Design', 'Web Development', 'Mobile App', 'UI/UX'],
  'additionalSkills': ['SQL Server',
   'Javascript',
   'Net Core',
   'MongoDB',
   'CSS',
   'React',
   'Python'],
  'profileSummary': 'Facere quae suscipit laboriosam labore recusandae minus. Accusamus illum vitae quisquam eaque.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 5,
  'downloads': 7,
  'hasCV': True,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 29,
  'experienceYears': 10,
  'salaryLacs': 9,
  'designation': 'Financial risk analyst',
  'department': 'HR',
  'industry': 'IT Services',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 16,
  'name': 'Darsh Koshy',
  'experience': '10y 7m',
  'salary': '₹ 35 Lacs',
  'location': 'Bareilly',
  'currentJob': 'Horticulturist, commercial',
  'company': 'Ray-Raju',
  'education': 'M.Tech IIT Bombay, Guwahati 2018',
  'preferredLocations': ['Pune', 'Delhi', 'Remote'],
  'keySkills': ['API Integration',
   'Frontend Development',
   'Backend',
   'Mobile App'],
  'additionalSkills': ['Kubernetes',
   'Python',
   'Angular',
   'MongoDB',
   'Software Development',
   'Docker',
   'Java'],
  'profileSummary': 'Quaerat placeat ullam. Molestias assumenda natus.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 17,
  'downloads': 10,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 145,
  'experienceYears': 10,
  'salaryLacs': 35,
  'designation': 'Research scientist (maths)',
  'department': 'Engineering',
  'industry': 'Finance',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 17,
  'name': 'Yashasvi Acharya',
  'experience': '8y 5m',
  'salary': '₹ 23 Lacs',
  'location': 'Amritsar',
  'currentJob': 'Horticultural consultant',
  'company': 'Nagy-Dara',
  'education': 'B.E. MIT Pune, Thane 2021',
  'preferredLocations': ['Chennai', 'Ahmedabad', 'Tirunelveli'],
  'keySkills': ['API Integration', 'DevOps', 'UI/UX', 'Mobile App'],
  'additionalSkills': ['Java',
   'Docker',
   'Angular',
   'Software Development',
   'SQL Server',
   'CSS',
   'HTML'],
  'profileSummary': 'Error consectetur nisi voluptatum facilis. A commodi itaque itaque esse. Quasi ratione nisi iusto.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 6,
  'downloads': 7,
  'hasCV': False,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 12,
  'experienceYears': 8,
  'salaryLacs': 23,
  'designation': 'Museum/gallery exhibitions officer',
  'department': 'Sales',
  'industry': 'Healthcare',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 18,
  'name': 'Dakshesh Madan',
  'experience': '5y 6m',
  'salary': '₹ 17 Lacs',
  'location': 'Pali',
  'currentJob': 'Barista',
  'company': 'Grewal Inc',
  'education': 'M.Tech IIT Bombay, Chennai 2018',
  'preferredLocations': ['Bangalore', 'Chennai', 'Mumbai'],
  'keySkills': ['Backend', 'Database Design', 'UI/UX', 'API Integration'],
  'additionalSkills': ['Docker',
   'Python',
   'SQL Server',
   'CSS',
   'Kubernetes',
   'Angular',
   'HTML'],
  'profileSummary': 'Modi temporibus nisi. Tenetur adipisci quasi itaque quae consectetur. Numquam similique sed.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 20,
  'downloads': 13,
  'hasCV': False,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 134,
  'experienceYears': 5,
  'salaryLacs': 17,
  'designation': 'Tourist information centre manager',
  'department': 'HR',
  'industry': 'Finance',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 19,
  'name': 'Ekapad Shroff',
  'experience': '9y 3m',
  'salary': '₹ 27 Lacs',
  'location': 'Agra',
  'currentJob': 'Public librarian',
  'company': 'Varghese, Sathe and Dhaliwal',
  'education': 'M.Tech Parul University, Warangal 2020',
  'preferredLocations': ['Mumbai', 'Tirunelveli', 'Remote'],
  'keySkills': ['Database Design', 'Server Side', 'Mobile App', 'DevOps'],
  'additionalSkills': ['Java',
   'SQL Server',
   'Node.js',
   'MongoDB',
   'CSS',
   'HTML',
   'React'],
  'profileSummary': 'Autem esse perferendis tenetur et harum quibusdam.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 1,
  'downloads': 4,
  'hasCV': False,
  'lastModified': 'yesterday',
  'activeStatus': 'Active today',
  'similarProfiles': 175,
  'experienceYears': 9,
  'salaryLacs': 27,
  'designation': 'Editor, film/video',
  'department': 'Engineering',
  'industry': 'Finance',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 20,
  'name': 'Samarth Balakrishnan',
  'experience': '10y 7m',
  'salary': '₹ 26 Lacs',
  'location': 'Bhiwandi',
  'currentJob': 'Event organiser',
  'company': 'Dar, Narasimhan and Hayer',
  'education': 'M.Tech Parul University, Chittoor 2023',
  'preferredLocations': ['Remote', 'Ahmedabad', 'Bangalore'],
  'keySkills': ['Backend', 'Database Design', 'API Integration', 'Mobile App'],
  'additionalSkills': ['Software Development',
   'Java',
   'Python',
   'Kubernetes',
   'HTML',
   'SQL Server',
   'Node.js'],
  'profileSummary': 'Adipisci aperiam sunt ullam eum ullam. Rem vitae quidem doloremque.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 20,
  'downloads': 2,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 176,
  'experienceYears': 10,
  'salaryLacs': 26,
  'designation': 'Dentist',
  'department': 'HR',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 21,
  'name': 'Chaitanya Andra',
  'experience': '6y 4m',
  'salary': '₹ 14 Lacs',
  'location': 'Thanjavur',
  'currentJob': 'Economist',
  'company': 'Modi-Deep',
  'education': 'B.Tech NIT Trichy, Jorhat 2018',
  'preferredLocations': ['Remote', 'Bangalore', 'Mumbai'],
  'keySkills': ['Mobile App',
   'Database Design',
   'API Integration',
   'Web Development'],
  'additionalSkills': ['Javascript',
   'Kubernetes',
   'CSS',
   'SQL Server',
   'HTML',
   'React',
   'MongoDB'],
  'profileSummary': 'Voluptatibus earum a quo. Labore unde iusto harum sed porro quisquam.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 10,
  'downloads': 17,
  'hasCV': True,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 160,
  'experienceYears': 6,
  'salaryLacs': 14,
  'designation': 'Personnel officer',
  'department': 'HR',
  'industry': 'IT Services',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 22,
  'name': 'Chandani Bedi',
  'experience': '6y 1m',
  'salary': '₹ 16 Lacs',
  'location': 'Mirzapur',
  'currentJob': 'Producer, television/film/video',
  'company': 'Puri, Vaidya and Saran',
  'education': 'M.Tech IIT Bombay, Begusarai 2018',
  'preferredLocations': ['Tirunelveli', 'Bangalore', 'Chennai'],
  'keySkills': ['UI/UX', 'Web Development', 'Backend', 'Frontend Development'],
  'additionalSkills': ['Javascript',
   'MongoDB',
   'Python',
   'Software Development',
   'CSS',
   'Kubernetes',
   'Docker'],
  'profileSummary': 'Consequuntur ad nemo quidem amet fugiat tempora. Assumenda nulla quod at.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 16,
  'downloads': 3,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 67,
  'experienceYears': 6,
  'salaryLacs': 16,
  'designation': 'Conservator, museum/gallery',
  'department': 'Sales',
  'industry': 'IT Services',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 23,
  'name': 'Charan Khosla',
  'experience': '0y 3m',
  'salary': '₹ 16 Lacs',
  'location': 'Jorhat',
  'currentJob': 'Regulatory affairs officer',
  'company': 'Golla-Contractor',
  'education': 'B.Tech NIT Trichy, Adoni 2023',
  'preferredLocations': ['Delhi', 'Ahmedabad', 'Bangalore'],
  'keySkills': ['Mobile App', 'Web Development', 'Backend', 'UI/UX'],
  'additionalSkills': ['CSS',
   'SQL Server',
   'HTML',
   'Node.js',
   'React',
   'Java',
   'Javascript'],
  'profileSummary': 'Cum fuga totam dolorum quisquam. Itaque neque ratione doloribus. Delectus saepe sit eum dolores.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 6,
  'downloads': 1,
  'hasCV': True,
  'lastModified': 'last week',
  'activeStatus': 'Active today',
  'similarProfiles': 76,
  'experienceYears': 0,
  'salaryLacs': 16,
  'designation': 'Communications engineer',
  'department': 'Sales',
  'industry': 'E-commerce',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 24,
  'name': 'Anusha Karan',
  'experience': '9y 2m',
  'salary': '₹ 8 Lacs',
  'location': 'Panipat',
  'currentJob': 'Nature conservation officer',
  'company': 'Kapadia, Dubey and Dube',
  'education': 'M.Tech Parul University, Jamalpur 2023',
  'preferredLocations': ['Pune', 'Bangalore', 'Remote'],
  'keySkills': ['API Integration',
   'Database Design',
   'Frontend Development',
   'UI/UX'],
  'additionalSkills': ['SQL Server',
   'Javascript',
   'Java',
   'Net Core',
   'Angular',
   'Node.js',
   'React'],
  'profileSummary': 'Iste ut dolor asperiores accusamus. Quae iusto voluptatum et placeat incidunt cum officiis.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 3,
  'downloads': 11,
  'hasCV': False,
  'lastModified': 'yesterday',
  'activeStatus': 'Active this week',
  'similarProfiles': 34,
  'experienceYears': 9,
  'salaryLacs': 8,
  'designation': 'Web designer',
  'department': 'HR',
  'industry': 'Finance',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 25,
  'name': 'Bimala Kapoor',
  'experience': '6y 1m',
  'salary': '₹ 28 Lacs',
  'location': 'Bhavnagar',
  'currentJob': 'Facilities manager',
  'company': 'Sani Group',
  'education': 'B.E. MIT Pune, Khammam 2022',
  'preferredLocations': ['Pune', 'Remote', 'Chennai'],
  'keySkills': ['Database Design',
   'Frontend Development',
   'UI/UX',
   'Mobile App'],
  'additionalSkills': ['CSS',
   'Kubernetes',
   'Angular',
   'Software Development',
   'HTML',
   'Net Core',
   'Python'],
  'profileSummary': 'Quisquam eligendi facilis ipsam id. Repellat corrupti sed possimus quos culpa veritatis voluptatem.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 19,
  'downloads': 5,
  'hasCV': False,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 121,
  'experienceYears': 6,
  'salaryLacs': 28,
  'designation': 'Actor',
  'department': 'Marketing',
  'industry': 'Healthcare',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 26,
  'name': 'Ira Chandra',
  'experience': '10y 2m',
  'salary': '₹ 14 Lacs',
  'location': 'New Delhi',
  'currentJob': 'Education officer, museum',
  'company': 'Bhatti-Bahl',
  'education': 'M.Tech IIT Bombay, Nadiad 2023',
  'preferredLocations': ['Tirunelveli', 'Chennai', 'Ahmedabad'],
  'keySkills': ['UI/UX', 'Server Side', 'Web Development', 'Backend'],
  'additionalSkills': ['Java',
   'Angular',
   'Net Core',
   'Javascript',
   'Kubernetes',
   'Software Development',
   'CSS'],
  'profileSummary': 'Sapiente eligendi ab voluptates. Suscipit explicabo eum consequuntur.\nVoluptates eligendi iusto.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 9,
  'downloads': 8,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active today',
  'similarProfiles': 56,
  'experienceYears': 10,
  'salaryLacs': 14,
  'designation': 'Quarry manager',
  'department': 'Sales',
  'industry': 'Healthcare',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 27,
  'name': 'Wahab Buch',
  'experience': '4y 3m',
  'salary': '₹ 20 Lacs',
  'location': 'Nagercoil',
  'currentJob': 'Insurance broker',
  'company': 'Rattan-Gopal',
  'education': 'B.E. Parul University, Aizawl 2022',
  'preferredLocations': ['Bangalore', 'Delhi', 'Chennai'],
  'keySkills': ['Frontend Development',
   'Backend',
   'Mobile App',
   'Server Side'],
  'additionalSkills': ['Net Core',
   'Kubernetes',
   'HTML',
   'SQL Server',
   'React',
   'Python',
   'MongoDB'],
  'profileSummary': 'Aspernatur in reiciendis magni.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 8,
  'downloads': 6,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active today',
  'similarProfiles': 36,
  'experienceYears': 4,
  'salaryLacs': 20,
  'designation': 'Equities trader',
  'department': 'Sales',
  'industry': 'Finance',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 28,
  'name': 'Amrita Vala',
  'experience': '1y 1m',
  'salary': '₹ 13 Lacs',
  'location': 'Srinagar',
  'currentJob': 'Financial risk analyst',
  'company': 'Nadig-Mane',
  'education': 'B.Tech Parul University, Kota 2023',
  'preferredLocations': ['Delhi', 'Remote', 'Ahmedabad'],
  'keySkills': ['API Integration', 'Database Design', 'Mobile App', 'Backend'],
  'additionalSkills': ['CSS',
   'Software Development',
   'HTML',
   'Angular',
   'React',
   'Python',
   'Net Core'],
  'profileSummary': 'Itaque commodi sit perspiciatis corrupti. Eveniet eum incidunt explicabo vitae.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 11,
  'downloads': 15,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 177,
  'experienceYears': 1,
  'salaryLacs': 13,
  'designation': 'Scientist, product/process development',
  'department': 'Marketing',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 29,
  'name': 'Ayush Vora',
  'experience': '8y 11m',
  'salary': '₹ 23 Lacs',
  'location': 'Rewa',
  'currentJob': 'Art gallery manager',
  'company': 'Char-Pal',
  'education': 'B.Tech NIT Trichy, Gurgaon 2020',
  'preferredLocations': ['Ahmedabad', 'Tirunelveli', 'Bangalore'],
  'keySkills': ['Database Design', 'API Integration', 'DevOps', 'Mobile App'],
  'additionalSkills': ['Kubernetes',
   'MongoDB',
   'Javascript',
   'Net Core',
   'Docker',
   'Node.js',
   'CSS'],
  'profileSummary': 'Eaque repellendus laborum temporibus beatae vel.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 16,
  'downloads': 7,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active this week',
  'similarProfiles': 14,
  'experienceYears': 8,
  'salaryLacs': 23,
  'designation': 'Special educational needs teacher',
  'department': 'Marketing',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 30,
  'name': 'Zansi Kunda',
  'experience': '9y 9m',
  'salary': '₹ 3 Lacs',
  'location': 'Kharagpur',
  'currentJob': 'Television camera operator',
  'company': 'Mane Inc',
  'education': 'B.E. Parul University, Nellore 2019',
  'preferredLocations': ['Tirunelveli', 'Pune', 'Mumbai'],
  'keySkills': ['API Integration', 'UI/UX', 'Web Development', 'Server Side'],
  'additionalSkills': ['HTML',
   'MongoDB',
   'Net Core',
   'Kubernetes',
   'Node.js',
   'SQL Server',
   'Java'],
  'profileSummary': 'Quam odio dolorum ipsum optio eligendi. Temporibus temporibus porro quos.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 2,
  'downloads': 14,
  'hasCV': True,
  'lastModified': 'last week',
  'activeStatus': 'Active today',
  'similarProfiles': 15,
  'experienceYears': 9,
  'salaryLacs': 3,
  'designation': 'Therapist, occupational',
  'department': 'HR',
  'industry': 'Healthcare',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 31,
  'name': 'Jeremiah Tandon',
  'experience': '8y 7m',
  'salary': '₹ 23 Lacs',
  'location': 'Khammam',
  'currentJob': 'Art gallery manager',
  'company': 'Jha-Reddy',
  'education': 'M.Tech NIT Trichy, Gaya 2023',
  'preferredLocations': ['Bangalore', 'Tirunelveli', 'Remote'],
  'keySkills': ['Web Development',
   'UI/UX',
   'Mobile App',
   'Frontend Development'],
  'additionalSkills': ['Java',
   'SQL Server',
   'MongoDB',
   'CSS',
   'Node.js',
   'React',
   'Kubernetes'],
  'profileSummary': 'Sequi a excepturi et. Aut officiis porro.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 2,
  'downloads': 14,
  'hasCV': False,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 200,
  'experienceYears': 8,
  'salaryLacs': 23,
  'designation': 'Print production planner',
  'department': 'Sales',
  'industry': 'Healthcare',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 32,
  'name': 'Yashasvi Bora',
  'experience': '6y 0m',
  'salary': '₹ 21 Lacs',
  'location': 'Nashik',
  'currentJob': 'Librarian, academic',
  'company': 'Ghose, Sethi and Naik',
  'education': 'B.E. MIT Pune, Agra 2020',
  'preferredLocations': ['Delhi', 'Ahmedabad', 'Pune'],
  'keySkills': ['Web Development',
   'Frontend Development',
   'UI/UX',
   'Server Side'],
  'additionalSkills': ['CSS',
   'MongoDB',
   'HTML',
   'Docker',
   'Javascript',
   'React',
   'SQL Server'],
  'profileSummary': 'Vitae repudiandae animi. Ex culpa molestias modi eius. Accusamus aperiam nobis quidem.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 13,
  'downloads': 11,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active this week',
  'similarProfiles': 112,
  'experienceYears': 6,
  'salaryLacs': 21,
  'designation': 'Theatre manager',
  'department': 'Marketing',
  'industry': 'IT Services',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 33,
  'name': 'Mugdha Shankar',
  'experience': '7y 2m',
  'salary': '₹ 18 Lacs',
  'location': 'Bhusawal',
  'currentJob': 'Television floor manager',
  'company': 'Kata, Sharma and Randhawa',
  'education': 'B.Tech MIT Pune, Bilaspur 2023',
  'preferredLocations': ['Pune', 'Delhi', 'Tirunelveli'],
  'keySkills': ['Mobile App', 'Backend', 'API Integration', 'Server Side'],
  'additionalSkills': ['Net Core',
   'Python',
   'Docker',
   'Angular',
   'Javascript',
   'MongoDB',
   'Java'],
  'profileSummary': 'Atque possimus harum aliquid totam maxime. Neque corrupti voluptas hic.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 18,
  'downloads': 0,
  'hasCV': True,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 93,
  'experienceYears': 7,
  'salaryLacs': 18,
  'designation': 'Research scientist (physical sciences)',
  'department': 'Marketing',
  'industry': 'Finance',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 34,
  'name': 'Osha Kurian',
  'experience': '4y 1m',
  'salary': '₹ 16 Lacs',
  'location': 'Jhansi',
  'currentJob': 'Market researcher',
  'company': 'Rajagopalan Ltd',
  'education': 'B.E. NIT Trichy, Dhule 2022',
  'preferredLocations': ['Pune', 'Tirunelveli', 'Bangalore'],
  'keySkills': ['Frontend Development',
   'Mobile App',
   'Backend',
   'API Integration'],
  'additionalSkills': ['SQL Server',
   'Java',
   'Angular',
   'CSS',
   'React',
   'Software Development',
   'Javascript'],
  'profileSummary': 'Nemo ducimus ab saepe dolores. Culpa nisi eveniet.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 19,
  'downloads': 9,
  'hasCV': False,
  'lastModified': 'last week',
  'activeStatus': 'Active today',
  'similarProfiles': 31,
  'experienceYears': 4,
  'salaryLacs': 16,
  'designation': 'Claims inspector/assessor',
  'department': 'HR',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 35,
  'name': 'Nihal Barman',
  'experience': '7y 9m',
  'salary': '₹ 18 Lacs',
  'location': 'Muzaffarpur',
  'currentJob': 'Administrator, Civil Service',
  'company': 'Goda, Ghosh and Bir',
  'education': 'B.Tech MIT Pune, Guna 2019',
  'preferredLocations': ['Delhi', 'Remote', 'Ahmedabad'],
  'keySkills': ['Web Development', 'DevOps', 'UI/UX', 'Mobile App'],
  'additionalSkills': ['React',
   'Javascript',
   'SQL Server',
   'CSS',
   'Software Development',
   'Angular',
   'Kubernetes'],
  'profileSummary': 'Nihil quisquam dolorem rerum. Recusandae id earum blanditiis. Nostrum esse ipsa.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 19,
  'downloads': 12,
  'hasCV': False,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active this week',
  'similarProfiles': 48,
  'experienceYears': 7,
  'salaryLacs': 18,
  'designation': 'Public affairs consultant',
  'department': 'Sales',
  'industry': 'E-commerce',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 36,
  'name': 'Chasmum Radhakrishnan',
  'experience': '0y 6m',
  'salary': '₹ 10 Lacs',
  'location': 'Silchar',
  'currentJob': 'Publishing rights manager',
  'company': 'Bora, Kapadia and Kamdar',
  'education': 'B.E. MIT Pune, Sri Ganganagar 2023',
  'preferredLocations': ['Chennai', 'Bangalore', 'Mumbai'],
  'keySkills': ['Backend',
   'Web Development',
   'Frontend Development',
   'Server Side'],
  'additionalSkills': ['Docker',
   'Python',
   'SQL Server',
   'Node.js',
   'Software Development',
   'HTML',
   'Javascript'],
  'profileSummary': 'Sit dolorem cumque rerum fugit. Perspiciatis dolorum similique velit asperiores.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 9,
  'downloads': 19,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active today',
  'similarProfiles': 75,
  'experienceYears': 0,
  'salaryLacs': 10,
  'designation': 'Chief Financial Officer',
  'department': 'Marketing',
  'industry': 'IT Services',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 37,
  'name': 'Charita Jain',
  'experience': '4y 2m',
  'salary': '₹ 1 Lacs',
  'location': 'Burhanpur',
  'currentJob': 'Therapeutic radiographer',
  'company': 'Narula, Prasad and Mohan',
  'education': 'B.Tech NIT Trichy, Tirupati 2018',
  'preferredLocations': ['Chennai', 'Remote', 'Pune'],
  'keySkills': ['UI/UX', 'Server Side', 'DevOps', 'Mobile App'],
  'additionalSkills': ['Angular',
   'Node.js',
   'Net Core',
   'Kubernetes',
   'Javascript',
   'React',
   'Python'],
  'profileSummary': 'Sit consequuntur ad praesentium iusto neque itaque. Ducimus explicabo eum expedita.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 7,
  'downloads': 8,
  'hasCV': False,
  'lastModified': 'last week',
  'activeStatus': 'Active today',
  'similarProfiles': 64,
  'experienceYears': 4,
  'salaryLacs': 1,
  'designation': 'Engineer, civil (consulting)',
  'department': 'HR',
  'industry': 'E-commerce',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 38,
  'name': 'Omaja Koshy',
  'experience': '6y 7m',
  'salary': '₹ 23 Lacs',
  'location': 'Panvel',
  'currentJob': 'Designer, graphic',
  'company': 'Biswas Group',
  'education': 'M.Tech Parul University, Silchar 2019',
  'preferredLocations': ['Ahmedabad', 'Bangalore', 'Pune'],
  'keySkills': ['Mobile App', 'API Integration', 'DevOps', 'Web Development'],
  'additionalSkills': ['Python',
   'React',
   'Node.js',
   'CSS',
   'Docker',
   'HTML',
   'Javascript'],
  'profileSummary': 'Omnis architecto voluptas natus. Cum molestiae adipisci suscipit.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 15,
  'downloads': 14,
  'hasCV': False,
  'lastModified': 'last week',
  'activeStatus': 'Active today',
  'similarProfiles': 153,
  'experienceYears': 6,
  'salaryLacs': 23,
  'designation': 'Research officer, government',
  'department': 'Engineering',
  'industry': 'Finance',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 39,
  'name': 'Girindra Bahri',
  'experience': '8y 11m',
  'salary': '₹ 4 Lacs',
  'location': 'Rajpur Sonarpur',
  'currentJob': 'Hospital pharmacist',
  'company': 'Bahl and Sons',
  'education': 'B.E. Parul University, Silchar 2018',
  'preferredLocations': ['Pune', 'Bangalore', 'Ahmedabad'],
  'keySkills': ['Backend', 'UI/UX', 'Server Side', 'DevOps'],
  'additionalSkills': ['React',
   'Software Development',
   'Net Core',
   'Angular',
   'Kubernetes',
   'Java',
   'Javascript'],
  'profileSummary': 'Dolor pariatur est error minima nulla. Molestiae culpa aperiam expedita totam tempora.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 0,
  'downloads': 10,
  'hasCV': True,
  'lastModified': 'last week',
  'activeStatus': 'Active this week',
  'similarProfiles': 53,
  'experienceYears': 8,
  'salaryLacs': 4,
  'designation': 'Trade union research officer',
  'department': 'Engineering',
  'industry': 'IT Services',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 40,
  'name': 'Bhavika Mitra',
  'experience': '3y 8m',
  'salary': '₹ 11 Lacs',
  'location': 'Tiruchirappalli',
  'currentJob': 'Fashion designer',
  'company': 'Morar Inc',
  'education': 'B.Tech Parul University, Nagpur 2018',
  'preferredLocations': ['Remote', 'Bangalore', 'Mumbai'],
  'keySkills': ['UI/UX', 'DevOps', 'API Integration', 'Frontend Development'],
  'additionalSkills': ['CSS',
   'React',
   'MongoDB',
   'Net Core',
   'Java',
   'Python',
   'Docker'],
  'profileSummary': 'Culpa vitae veritatis aliquid fugiat quaerat. Eveniet natus asperiores dolorem ea labore.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 7,
  'downloads': 9,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active today',
  'similarProfiles': 73,
  'experienceYears': 3,
  'salaryLacs': 11,
  'designation': 'Data processing manager',
  'department': 'Engineering',
  'industry': 'Finance',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 41,
  'name': 'Daksh Pal',
  'experience': '4y 10m',
  'salary': '₹ 32 Lacs',
  'location': 'Bulandshahr',
  'currentJob': 'Engineer, control and instrumentation',
  'company': 'Krishnamurthy LLC',
  'education': 'B.Tech Parul University, Hajipur 2024',
  'preferredLocations': ['Tirunelveli', 'Chennai', 'Ahmedabad'],
  'keySkills': ['API Integration', 'UI/UX', 'Database Design', 'Server Side'],
  'additionalSkills': ['SQL Server',
   'HTML',
   'CSS',
   'Python',
   'Net Core',
   'Angular',
   'Node.js'],
  'profileSummary': 'Sint facilis consequuntur. Quos laboriosam aliquid iusto qui. Consequuntur ut minus natus ipsum.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 16,
  'downloads': 18,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 170,
  'experienceYears': 4,
  'salaryLacs': 32,
  'designation': 'Furniture conservator/restorer',
  'department': 'Marketing',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 42,
  'name': 'Owen Bala',
  'experience': '6y 9m',
  'salary': '₹ 34 Lacs',
  'location': 'Shahjahanpur',
  'currentJob': 'Sports development officer',
  'company': 'Jayaraman PLC',
  'education': 'B.Tech Parul University, Tiruvottiyur 2019',
  'preferredLocations': ['Delhi', 'Remote', 'Mumbai'],
  'keySkills': ['API Integration',
   'Mobile App',
   'Frontend Development',
   'Server Side'],
  'additionalSkills': ['Net Core',
   'Python',
   'Angular',
   'Docker',
   'React',
   'Software Development',
   'Node.js'],
  'profileSummary': 'Velit alias animi iusto nobis beatae non. Nesciunt repellat hic a hic sit magnam dicta.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 7,
  'downloads': 5,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active this week',
  'similarProfiles': 129,
  'experienceYears': 6,
  'salaryLacs': 34,
  'designation': 'Chief Executive Officer',
  'department': 'Marketing',
  'industry': 'Healthcare',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': False},
 {'id': 43,
  'name': 'Leela Borra',
  'experience': '8y 5m',
  'salary': '₹ 14 Lacs',
  'location': 'Karawal Nagar',
  'currentJob': 'Further education lecturer',
  'company': 'Tiwari, Gala and Grewal',
  'education': 'B.E. IIT Bombay, Erode 2021',
  'preferredLocations': ['Remote', 'Tirunelveli', 'Bangalore'],
  'keySkills': ['UI/UX', 'Database Design', 'Web Development', 'DevOps'],
  'additionalSkills': ['Angular',
   'SQL Server',
   'Net Core',
   'Javascript',
   'Java',
   'MongoDB',
   'HTML'],
  'profileSummary': 'Quod accusantium omnis aliquid dignissimos earum architecto. Accusamus quas vero.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 2,
  'downloads': 5,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 160,
  'experienceYears': 8,
  'salaryLacs': 14,
  'designation': 'Dispensing optician',
  'department': 'Engineering',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 44,
  'name': 'Jairaj Sharaf',
  'experience': '5y 9m',
  'salary': '₹ 5 Lacs',
  'location': 'Jalna',
  'currentJob': 'Video editor',
  'company': 'Virk Inc',
  'education': 'B.Tech Parul University, Raurkela Industrial Township 2019',
  'preferredLocations': ['Ahmedabad', 'Bangalore', 'Remote'],
  'keySkills': ['API Integration', 'Web Development', 'UI/UX', 'Server Side'],
  'additionalSkills': ['Javascript',
   'Angular',
   'Net Core',
   'Software Development',
   'HTML',
   'MongoDB',
   'React'],
  'profileSummary': 'Necessitatibus culpa amet maiores quaerat vitae.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 9,
  'downloads': 18,
  'hasCV': False,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 150,
  'experienceYears': 5,
  'salaryLacs': 5,
  'designation': 'Community arts worker',
  'department': 'HR',
  'industry': 'Finance',
  'isNewProfile': True,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 45,
  'name': 'Faraj Sarin',
  'experience': '3y 8m',
  'salary': '₹ 33 Lacs',
  'location': 'Bhubaneswar',
  'currentJob': 'Fast food restaurant manager',
  'company': 'Lad, Sarraf and Nagy',
  'education': 'M.Tech IIT Bombay, Hosur 2019',
  'preferredLocations': ['Tirunelveli', 'Bangalore', 'Mumbai'],
  'keySkills': ['DevOps', 'Backend', 'Server Side', 'Mobile App'],
  'additionalSkills': ['Java',
   'Javascript',
   'HTML',
   'Python',
   'SQL Server',
   'MongoDB',
   'Node.js'],
  'profileSummary': 'Atque quas optio laborum. Placeat molestias id unde doloribus accusantium.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 17,
  'downloads': 16,
  'hasCV': False,
  'lastModified': 'yesterday',
  'activeStatus': 'Active today',
  'similarProfiles': 117,
  'experienceYears': 3,
  'salaryLacs': 33,
  'designation': 'Education officer, environmental',
  'department': 'HR',
  'industry': 'IT Services',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 46,
  'name': 'Bahadurjit More',
  'experience': '3y 8m',
  'salary': '₹ 1 Lacs',
  'location': 'Kolkata',
  'currentJob': 'Magazine journalist',
  'company': 'Chawla, Kakar and Jayaraman',
  'education': 'B.Tech NIT Trichy, Indore 2018',
  'preferredLocations': ['Bangalore', 'Delhi', 'Remote'],
  'keySkills': ['Backend', 'UI/UX', 'Database Design', 'DevOps'],
  'additionalSkills': ['Java',
   'Net Core',
   'HTML',
   'Python',
   'CSS',
   'React',
   'SQL Server'],
  'profileSummary': 'Est aperiam eum dignissimos iure. Tempore eum animi. Cupiditate tempora ea illum.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 8,
  'downloads': 5,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active today',
  'similarProfiles': 120,
  'experienceYears': 3,
  'salaryLacs': 1,
  'designation': 'Systems analyst',
  'department': 'Marketing',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': True},
 {'id': 47,
  'name': 'Samesh Verma',
  'experience': '1y 5m',
  'salary': '₹ 34 Lacs',
  'location': 'Ongole',
  'currentJob': 'Teaching laboratory technician',
  'company': 'Zachariah, Dhar and Chaudhary',
  'education': 'B.Tech IIT Bombay, Ambala 2019',
  'preferredLocations': ['Bangalore', 'Remote', 'Tirunelveli'],
  'keySkills': ['Backend', 'Server Side', 'Mobile App', 'DevOps'],
  'additionalSkills': ['SQL Server',
   'Node.js',
   'Java',
   'Docker',
   'Net Core',
   'Kubernetes',
   'Python'],
  'profileSummary': 'Non vitae quod consequatur mollitia natus beatae fuga.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 6,
  'downloads': 10,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 122,
  'experienceYears': 1,
  'salaryLacs': 34,
  'designation': 'Art therapist',
  'department': 'HR',
  'industry': 'Healthcare',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 48,
  'name': 'Yagnesh Balasubramanian',
  'experience': '4y 4m',
  'salary': '₹ 38 Lacs',
  'location': 'Nizamabad',
  'currentJob': 'Merchandiser, retail',
  'company': 'Chhabra-Bhatia',
  'education': 'B.Tech IIT Bombay, Navi Mumbai 2021',
  'preferredLocations': ['Mumbai', 'Remote', 'Chennai'],
  'keySkills': ['Frontend Development', 'Mobile App', 'Backend', 'DevOps'],
  'additionalSkills': ['Docker',
   'Software Development',
   'React',
   'HTML',
   'Java',
   'Angular',
   'Python'],
  'profileSummary': 'Sit provident debitis officia. Voluptatem id tempore nesciunt rem nesciunt nisi aspernatur.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 7,
  'downloads': 14,
  'hasCV': True,
  'lastModified': 'yesterday',
  'activeStatus': 'Active today',
  'similarProfiles': 34,
  'experienceYears': 4,
  'salaryLacs': 38,
  'designation': 'Microbiologist',
  'department': 'Marketing',
  'industry': 'Finance',
  'isNewProfile': True,
  'isPremiumInstitute': False,
  'hasVerifiedSkills': True},
 {'id': 49,
  'name': 'Dhriti Borah',
  'experience': '10y 10m',
  'salary': '₹ 13 Lacs',
  'location': 'Farrukhabad',
  'currentJob': 'Chief Technology Officer',
  'company': 'Ravi, Soni and Jha',
  'education': 'B.E. IIT Bombay, Burhanpur 2019',
  'preferredLocations': ['Delhi', 'Mumbai', 'Ahmedabad'],
  'keySkills': ['Server Side', 'Database Design', 'UI/UX', 'DevOps'],
  'additionalSkills': ['Java',
   'Javascript',
   'Kubernetes',
   'CSS',
   'Angular',
   'Docker',
   'SQL Server'],
  'profileSummary': 'Architecto perspiciatis possimus odit sequi. Expedita vel veritatis corporis.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 15,
  'downloads': 17,
  'hasCV': True,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 145,
  'experienceYears': 10,
  'salaryLacs': 13,
  'designation': 'Forensic scientist',
  'department': 'Marketing',
  'industry': 'IT Services',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False},
 {'id': 50,
  'name': 'Umang Nigam',
  'experience': '9y 2m',
  'salary': '₹ 33 Lacs',
  'location': 'Patna',
  'currentJob': 'Amenity horticulturist',
  'company': 'Bhasin-Boase',
  'education': 'B.E. NIT Trichy, Bhiwandi 2024',
  'preferredLocations': ['Remote', 'Bangalore', 'Mumbai'],
  'keySkills': ['Server Side',
   'Frontend Development',
   'Database Design',
   'Web Development'],
  'additionalSkills': ['Net Core',
   'Kubernetes',
   'Software Development',
   'React',
   'HTML',
   'Python',
   'Angular'],
  'profileSummary': 'Blanditiis placeat sapiente excepturi aperiam placeat. Possimus quia officia rem beatae culpa.',
  'photo': '/placeholder.svg?height=80&width=80',
  'views': 3,
  'downloads': 1,
  'hasCV': False,
  'lastModified': 'last 2 months',
  'activeStatus': 'Active today',
  'similarProfiles': 154,
  'experienceYears': 9,
  'salaryLacs': 33,
  'designation': 'Conservation officer, historic buildings',
  'department': 'Marketing',
  'industry': 'E-commerce',
  'isNewProfile': False,
  'isPremiumInstitute': True,
  'hasVerifiedSkills': False}]